name: dart_project          # Name of your project
description: A Dart project for learning data types, control flow, and loops
version: 1.0.0              # Version of the project

# Environment settings - specify Dart SDK version constraints
environment:
  sdk: '>=2.12.0 <3.0.0'    # Minimum and maximum supported Dart versions

# Dependencies for your project
dependencies:
  http: ^0.13.3             # Add the http package once
  path: ^1.8.1              # Example dependency (can be removed if not needed)

# Dev dependencies for development tools (optional)
dev_dependencies:
  test: ^1.16.0             # Testing framework for Dart


